[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.2",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

